
root_folder: "./data/update_v2_laser_velocity_xz_cross_section_data"
downscale_method: "lanczos" 
n_steps: "1" 

residual_flag: false
conditioning: "implicit"
encoding: False

normalize_method: "standardize"
schedule: "linear"
fields: 'temperature'

timesteps: 1000
batch_size: 16
epochs: 300
learning_rate: 5e-5
use_pretrained: False
encoder_results_dir: '/home/cmu/github/LPBFDiffusionSR/runs/direct/encoder/2023_01_23_03_50_44/standardize/n_steps_1'
  

