
root_folder: "/home/oogoke/DiffusionSR/datasets/update_v2_laser_velocity_xz_cross_section_data"
downscale_method: "direct" 
n_steps: "3" 

residual_flag: false
conditioning: "implicit"


normalize_method: "standardize"
schedule: "linear"
fields: 'temperature'
restart_dir: '/home/oogoke/DiffusionSR/runs/clean/direct/diffusionno_residual/2023_01_04_21_59_47/standardize/n_steps_3'  
timesteps: 2000
batch_size: 16
epochs: 400
learning_rate: 5e-5
use_pretrained: True
encoder_results_dir: '/home/oogoke/DiffusionSR/runs/clean/direct/encoder/2023_01_04_21_59_47/standardize/n_steps_3'
  

