
root_folder: "/home/oogoke/DiffusionSR/datasets/simulation_basis_v3_laser_velocity_xz_cross_section_data"
downscale_method: "direct" 
n_steps: "1" 

residual_flag: false
conditioning: "implicit"
encoding: True


normalize_method: "standardize"
schedule: "linear"
fields: 'temperature'
loss_type: 'huber'
timesteps: 1000
batch_size: 16
epochs: 300
learning_rate: 5e-5
use_pretrained: False













































































































































































































































































































































































































































































































































































































































































































































































































































































































































