
root_folder: "./data/ss316l_v2_all_laser_velocity_xz_cross_section_data"
downscale_method: "direct" 
n_steps: "1" 

residual_flag: false
conditioning: "implicit"


normalize_method: "standardize"
schedule: "quadratic"
fields: "temperature"
timesteps: 1000
batch_size: 16
epochs: 300
learning_rate: 5e-5
use_pretrained: False
encoder_results_dir: './runs/direct/encoder/2023_01_30_03_21_51/standardize/n_steps_1'
  

