
root_folder: "./data/expanded_ss316l_all_laser_velocity_xz_cross_section_data_expanded_frame"
downscale_method: "direct" 
n_steps: "1" 
encoding: False
residual_flag: false
conditioning: "implicit"


normalize_method: "standardize"
schedule: "linear"
fields: 'temperature'
timesteps: 1000
batch_size: 20
epochs: 300
learning_rate: 5e-5
use_pretrained: False
#restart_dir: './runs/direct/diffusionimplicitencoded/2026_04_22_22_48_29/standardize/n_steps_1'
#encoder_results_dir: './runs/direct/encoder/2026_04_22_22_48_29/standardize/n_steps_1'
  


inflate_dim: 4
inflate_method: 'repeat'

voxel_save_interval: 50
voxel_sample_batch_idx: 100
voxel_threshold: 1800.0
voxel_channel: 0
voxel_sampler: "DDIM"
voxel_skip: 10